default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.1.0'
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: sort-simple-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.6.2'
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.32.0'
    hooks:
      - id: yapf
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: 'v3.4.3-1'
    hooks:
      - id: shfmt
        args: ['-w', '-i', '2', '-s', '-l', '-ci']
  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: '0.50.0'
    hooks:
      - id: swiftformat
