default_stages: [commit]
repos:
  # >>>>>>>>>>>>>>>>>>>>> basic <<<<<<<<<<<<<<<<<<<< #
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: sort-simple-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0-alpha.4'
    hooks:
      - id: prettier
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 'v2.39.1'
    hooks:
      - id: commitizen
        stages: [commit-msg]
  # >>>>>>>>>>>>>>>>>>>>> basic <<<<<<<<<<<<<<<<<<<< #

  # >>>>>>>>>>>>>>>>>>>>> bash <<<<<<<<<<<<<<<<<<<< #
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: 'v3.6.0-1'
    hooks:
      - id: shfmt
        args: ['-w', '-i', '2', '-s', '-l', '-ci']
  # >>>>>>>>>>>>>>>>>>>>> bash <<<<<<<<<<<<<<<<<<<< #

  # >>>>>>>>>>>>>>>>>>>>> python <<<<<<<<<<<<<<<<<<<< #
  # - repo: https://github.com/pre-commit/mirrors-yapf
  #   rev: 'v0.32.0'
  #   hooks:
  #     - id: yapf
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v3.3.1'
    hooks:
      - id: pyupgrade
  - repo: https://github.com/PyCQA/isort
    rev: '5.11.4'
    hooks:
      - id: isort
        args: ['--line-length=100']
  # >>>>>>>>>>>>>>>>>>>>> python <<<<<<<<<<<<<<<<<<<< #

  # >>>>>>>>>>>>>>>>>>>>> swift <<<<<<<<<<<<<<<<<<<< #
  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: '0.50.7'
    hooks:
      - id: swiftformat
        args: ['--swiftversion', '5.7.1']
  # >>>>>>>>>>>>>>>>>>>>> swift <<<<<<<<<<<<<<<<<<<< #
